# Generated by Django 3.2.7 on 2021-09-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(related_name='module', to='course.Module'),
        ),
    ]
