# Generated by Django 3.2.7 on 2021-09-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210903_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(null=True, related_name='module', to='course.Module'),
        ),
    ]
