# Generated by Django 3.2.7 on 2021-09-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
