# Generated by Django 3.2.7 on 2021-09-04 20:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20210904_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='text_store',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
