# Generated by Django 3.2.7 on 2021-09-03 19:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default=datetime.datetime(2021, 9, 3, 19, 45, 58, 705387, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
